### ISSUE TITLE
Pull and update vacant units for ACS 2012-16. 

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/IPUMS#12]
@ptatian - are there any instructions on what needs to be pull from IPUMS for the vacant units file? 

I see this program reads it in: L:\Libraries\IPUMS\Prog\ACS_2009_11_vacant.sas

cc @rpitingolo

**Comment by ptatian** [comment]
@lhendey @rpitingolo No instructions. You should extract the data in **household** format, not person format. You only need to select the housing unit characteristics and you can filter on vacant units (VACANCY = 1 - 9).

**Comment by lhendey** [comment]
@rpitingolo - can you do this one?

**Comment by rpitingolo** [comment]
@lhendey I've got the code ready for this. For some reason the extract is taking hours. Hopefully it will be ready soon and then I can test and do a pull request.
