### ISSUE TITLE
Add missing LANGUAGED var to Ipums.Acs_2012_16

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/IPUMS#13]
[According to IPUMS](http://answers.popdata.org/Are-language-spoken-variables-LANGUAGE-LANGUAGED-2016-ACS-US-file-Any-alternatives-q2366517.aspx), the LANGUAGED variable is not yet available for the ACS 2016 data. [IPUMS will post an announcement](https://usa.ipums.org/usa-action/revisions) when the variable has been added to their files. 

We should continue to monitor this issue and, once the new data are available, we should add the missing variable to our Ipums.Acs_2012_16 data set.

**Comment by ptatian** [comment]
@rpitingolo IPUMS has said that the LANGUAGED variable has now been added to the 2012-16 ACS microdata. We should update our files with this variable. I don't know whether it is easier to just redownload everything, or just download the one variable and then merge it on to the file. I'll let you decide.

**Comment by rpitingolo** [comment]
@ptatian Thanks. I think it's easier to download one variable and merge it on, because I recall Yipeng was running into file size errors in their query system when trying to do everything.

**Comment by rpitingolo** [comment]
@ptatian this is finished. I had to update the formats for language and languagd because there were some new codes that weren't in  the library previously.

**Comment by ptatian** [comment]
@rpitingolo Thanks, Rob.
