### ISSUE TITLE
pull vacant units for 2013-2017 single year files

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/IPUMS#20]
charge metro holding account (for Regional Housing Framework)

**Comment by rpitingolo** [comment]
@lhendey it's taking a really long time for the ipums extract to create the file (about 40 minutes and counting). I have to leave soon but hopefully by the time I get home it's ready and then I can run it.

**Comment by rpitingolo** [comment]
@lhendey took an hour and a half but first extract ran fine. Just waiting on the others.

**Comment by lhendey** [comment]
@rpitingolo is that normal? I wouldn't think these files would be as bad.

**Comment by rpitingolo** [comment]
@lhendey not normal from my experience, but I recall Yipeng experienced some slowness during the last update. The files are only about 10MB so it's not a size issue.
