### ISSUE TITLE
pull households and vacant units for North carolina

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/IPUMS#24]
Yipeng - go ahead and pull all the standard vars you would for DC.

**Comment by maggiesu0725** [comment]
@lhendey just to confirm I'm saving raw data in the raw folder and read the data in our ipums library?

**Comment by lhendey** [comment]
@maggiesu0725 yes!

**Comment by maggiesu0725** [comment]
ACS_2017_vacant_NC.log ~ ACS_2012_vacant_NC.log
ACS_2017_NC.log ~ ACS_2012_NC.log
