### ISSUE TITLE
Create ACS 2014-18 data

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/IPUMS#28]
Download ACS 2014-2018 5-Year sample data from IPUMS USA website and create DC, MD, VA, and WV extract files.

**Comment by rpitingolo** [comment]
@eleanorble here are the instructions: https://urbanorg.app.box.com/file/646295988300

Thanks!

**Comment by owennnnoble** [comment]
@rpitingolo I pushed the changes to update-#28, but I'm having trouble reading in the IPUMS data from the L drive.

**Comment by rpitingolo** [comment]
@eleanorble thanks. I'll take a look now.

**Comment by owennnnoble** [comment]
@rpitingolo L:\Libraries\IPUMS\Prog\ACS_2014_18.log log ran with no errors

**Comment by rpitingolo** [comment]
@ptatian you should be able to use this data now for your analysis. There are a few new formats that we need to add and then re-batch submit, but I will do that in a separate issue.

**Comment by ptatian** [comment]
Great. Thank you, @rpitingolo and @eleanorble!
