### ISSUE TITLE
Download IPUMS ACS 2018-22

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/IPUMS#33]
Instructions https://urbanorg.app.box.com/file/646295988300

**Comment by akort15** [comment]
@lhendey I opened a pull request for the vacancy piece here, once you approve we can re-close this issue: https://github.com/NeighborhoodInfoDC/IPUMS/pull/35

**Comment by lhendey** [comment]
"\\sas1\dcdata\Libraries\IPUMS\Prog\ACS_2018_22_vacant.log"
"\\sas1\dcdata\Libraries\IPUMS\Prog\ACS_2018_22.log"
