### ISSUE TITLE
Set up L: sync

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/IPUMS#8]
Instructions: https://urbanorg.app.box.com/notes/263729676921
Branch: `develop-#8`

**Comment by ptatian** [comment]
@rpitingolo Would you please take care of this issue when you have a moment? Thanks.

**Comment by rpitingolo** [comment]
@ptatian I'm getting an error on the 1st (rename) step because it says the folder is open by another program. Doesn't seem like I have anything open on my end. Do you? Also @maggiesu0725 can you check? Thanks.

**Comment by ptatian** [comment]
@rpitingolo I don't think it's me. I don't have anything open in that folder.

**Comment by rpitingolo** [comment]
@ptatian I just got it to work.

**Comment by rpitingolo** [comment]
@ptatian this is complete.
