### ISSUE TITLE
Update ACS 2012-16 data

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/IPUMS#9]

**Comment by rpitingolo** [comment]
@maggiesu0725 We have a new set of iPums data to process for NIDC. Please find me and I will show you the instructions.

**Comment by ptatian** [comment]
@maggiesu0725 We now have a charge code for the DC SOI/SOAA project, which is 101658-0001-001. We will want to split the charges with the DC large units study, for which we don't yet have a charge code. So, please charge 1/2 time to DC SOI/SOAA and 1/2 to Metro Center holding, which we will later change to the large units code. 

Please begin this work as soon as you can and let @rpitingolo or me know if you have any questions. Thank you! cc: @lhendey

**Comment by ptatian** [comment]
Hi @maggiesu0725. Just checking in. Have you been able to start on this yet?

**Comment by maggiesu0725** [comment]
@ptatian I started a little and then was working on the tables, Will work on it today.

**Comment by ptatian** [comment]
Great. Thanks!

**Comment by maggiesu0725** [comment]
@rpitingolo  all updates in this task have been committed, please review. Thanks!

**Comment by rpitingolo** [comment]
@maggiesu0725 thanks. I will review.

**Comment by rpitingolo** [comment]
@maggiesu0725 did you do a pull request? Please do a pull request if not.

**Comment by maggiesu0725** [comment]
@rpitingolo yes i did?

**Comment by ptatian** [comment]
@rpitingolo @maggiesu0725 Checking in on this. We need to get it wrapped up ASAP. Thank you.

**Comment by rpitingolo** [comment]
@ptatian will get this finished today. @maggiesu0725

**Comment by rpitingolo** [comment]
@ptatian @maggiesu0725 this update is complete.

**Comment by ptatian** [comment]
Thank you.

**Comment by lhendey** [comment]
@rpitingolo - we didn't download the vacant units did we?

**Comment by rpitingolo** [comment]
@lhendey I forget, is there a special option that needs to be turned on to download the vacant units? I re-read the instructions and it says to download the household and person data but no options beyond that.

**Comment by lhendey** [comment]
@rpitingolo - yes, i think you have to download it as a separate file and it can't be downloaded as part of the household file. i'll create a new issue (Peter probably has details).
